name: CI Terraform Infrastructure

on:
  pull_request:
    branches: [ "dev" ]

  workflow_dispatch:

jobs:
  build_infra:
    name: "Build AWS Infrastructure via Terraform"
    runs-on: ubuntu-latest
    
    defaults:
      run:
        shell: bash
    
    steps:
      - name: 'Checkout'
      - uses: actions/checkout@v3

      - name: Configure AWS credentials
        uses: aws-actions/configure-aws-credentials@v2
        with:
          aws-region: ${{ vars.AWS_REGION }}
          aws-access-key-id: ${{ secrets.AWS_ACCESS_KEY_ID }}
          aws-secret-access-key: ${{ secrets.AWS_SECRET_ACCESS_KEY }}
      
      - name: 'Setup Terraform'
        uses: hashicorp/setup-terraform@v1
        with:
          terraform_version: ">=1.1.0"

      - name: 'Terraform Init'
        run: terraform init
        working-directory: ./terraform

      - name: 'Terraform Format'
        run: terraform fmt
        working-directory: ./terraform
        
      - name: 'Terraform Plan'
        run: terraform plan
        working-directory: ./terraform
